baseurl: /
title: PJCL
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: ''
disqusShortname: ''

minify:
    disableXML: true
    # minifyOutput: true

# languages:
#     en:
#         languageName: ":eng:"
#         languageAltTitle: English
#         weight: 1
#         menu:
#             main:
#                 - name: Archive
#                   url: archives
#                   weight: 5
#                 - name: Search
#                   url: search/
#                   weight: 10
#                 - name: Tags
#                   url: tags/
#                   weight: 10
#                 - name: Categories
#                   url: categories/
#                   weight: 10
#     es:
#         languageName: ":sp:"
#         languageAltTitle: Español
#         weight: 2
#         menu:
#             main:
#                 - name: Archivo
#                   url: archives
#                   weight: 5
#                 - name: Búsqueda
#                   url: search/
#                   weight: 10
#                 - name: Tags
#                   url: tags/
#                   weight: 10
#                 - name: Categorias
#                   url: categories/
#                   weight: 10
#     fr:
#         languageName: ":fr:"
#         languageAltTitle: Français
#         weight: 2
#         menu:
#             main:
#                 - name: Archive
#                   url: archives
#                   weight: 5
#                 - name: Search
#                   url: search/
#                   weight: 10
#                 - name: Tags
#                   url: tags/
#                   weight: 10
#                 - name: Categories
#                   url: categories/
#                   weight: 10
                  
languageCode: en-us

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

outputs:
    home:
        - HTML
        - RSS
        - JSON
        
permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
    # - name: About
    #   url: /about/
    - name: Archive
      url: archives      
    - name: Categories
      url: /categories/      
    - name: Search
      url: /search/
    - name: Tags
      url: /tags/      
    # - name: GitHub
    #   url: https://github.com/rstudio/blogdown
    # - name: Canvas
    #   url: https://cursos.canvas.uc.cl
    
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "PSI2302, notas y otros"
  author: PJCL
  
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0

  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
    
  cover:
    linkFullImages: true 
    

  
  defaultTheme: auto
   # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
        - name: Archives
          url: archives
        - name: Tags
          url: tags
          
  homeInfoParams:
      Title: "Hola"
      # Content: >
      #     Welcome to demo of hugo's theme PaperMod.
      #     - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
      #     - Do give a 🌟 on Github !
      #     - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
  socialIcons:
      - name: github
        url: "https://github.com/pjcarozzi"
      - name: twitter
        url: "https://"
      - name: "Canvas"
        url: "!"
      - name: email
        url: "https://"
      - name: RsS
        url: "index.xml"

  editPost:
      URL: "mailto://pjcarozzi@uc.cl?subject=Suggesting changes for "
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
  
    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

